all:
  children:
    bootstrap_controlplane:
      hosts:
        homelab-2: {}
    controlplane:
      hosts:
        homelab-0: {}
        homelab-1: {}
        homelab-2: {}
    controlplane_workers:
      hosts:
        homelab-1: {}
        homelab-2: {}
    worker:
      hosts: {}
